spring:
  datasource:
    #    dữ liệu demo thì dùng cái này nha, t insert kha khá dữ liệu
    #    url: jdbc:postgresql://autorack.proxy.rlwy.net:22714/railway
    #    username: postgres
    #    password: TmLNwENGlfiUstybmRzfRUQimmPJiyJq

    url: jdbc:postgresql://localhost:5432/Planfortrips
    #    username: postgres
    #    password: 123
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
api:
  prefix: api/v1

cloudinary:
  cloud_name: dzbtsco86
  api_key: 458554894698284
  api_secret: 5JqucoX6jWiaB4xikpQb5wpjbJo