spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Planfortrips
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    converters:
      preferred-json-mapper: gson.
api:
  prefix : api/v1

